import type { BenchmarkInput } from "../types/benchmark.types";

type Defaults = Omit<BenchmarkInput, "sector" | "fuente">;

export const BENCHMARK_DEFAULTS: Record<string, Defaults & { fuente: string }> = {
  inmobiliaria: {
    ctr_excelente: 3.5,  ctr_aceptable: 1.5,
    cpc_excelente: 4.0,  cpc_aceptable: 8.0,
    cpm_excelente: 55,   cpm_aceptable: 90,
    cpl_excelente: 80,   cpl_aceptable: 180,
    cpa_excelente: 200,  cpa_aceptable: 500,
    roas_excelente: 5,   roas_aceptable: 3,
    roi_excelente: 200,  roi_aceptable: 100,
    fuente: "WordStream Real Estate 2024, Meta LatAm Benchmarks 2024",
  },
  salud: {
    ctr_excelente: 4.5,  ctr_aceptable: 2.0,
    cpc_excelente: 3.0,  cpc_aceptable: 6.5,
    cpm_excelente: 45,   cpm_aceptable: 75,
    cpl_excelente: 55,   cpl_aceptable: 120,
    cpa_excelente: 90,   cpa_aceptable: 200,
    roas_excelente: 6,   roas_aceptable: 3,
    roi_excelente: 250,  roi_aceptable: 120,
    fuente: "WordStream Healthcare 2024, Google Ads Health Industry Report",
  },
  educacion: {
    ctr_excelente: 3.5,  ctr_aceptable: 1.8,
    cpc_excelente: 2.5,  cpc_aceptable: 5.5,
    cpm_excelente: 38,   cpm_aceptable: 65,
    cpl_excelente: 45,   cpl_aceptable: 110,
    cpa_excelente: 130,  cpa_aceptable: 280,
    roas_excelente: 5,   roas_aceptable: 2.5,
    roi_excelente: 200,  roi_aceptable: 100,
    fuente: "WordStream Education 2024, Meta Education Industry Benchmarks",
  },
  comercio_retail: {
    ctr_excelente: 5.0,  ctr_aceptable: 2.5,
    cpc_excelente: 1.5,  cpc_aceptable: 3.5,
    cpm_excelente: 28,   cpm_aceptable: 52,
    cpl_excelente: 30,   cpl_aceptable: 75,
    cpa_excelente: 55,   cpa_aceptable: 120,
    roas_excelente: 8,   roas_aceptable: 4,
    roi_excelente: 300,  roi_aceptable: 150,
    fuente: "WordStream Retail 2024, Meta Commerce Benchmarks LatAm",
  },
  comercio_mayorista: {
    ctr_excelente: 2.5,  ctr_aceptable: 1.2,
    cpc_excelente: 2.5,  cpc_aceptable: 5.5,
    cpm_excelente: 38,   cpm_aceptable: 68,
    cpl_excelente: 55,   cpl_aceptable: 130,
    cpa_excelente: 110,  cpa_aceptable: 240,
    roas_excelente: 6,   roas_aceptable: 3,
    roi_excelente: 220,  roi_aceptable: 110,
    fuente: "Google Ads B2B Benchmarks 2024, WordStream B2B",
  },
  construccion: {
    ctr_excelente: 2.5,  ctr_aceptable: 1.2,
    cpc_excelente: 5.0,  cpc_aceptable: 10.0,
    cpm_excelente: 60,   cpm_aceptable: 100,
    cpl_excelente: 95,   cpl_aceptable: 210,
    cpa_excelente: 190,  cpa_aceptable: 420,
    roas_excelente: 5,   roas_aceptable: 2.5,
    roi_excelente: 200,  roi_aceptable: 100,
    fuente: "WordStream Construction 2024, Meta B2B LatAm Report",
  },
  arquitectura_ingenieria: {
    ctr_excelente: 2.5,  ctr_aceptable: 1.2,
    cpc_excelente: 5.5,  cpc_aceptable: 11.0,
    cpm_excelente: 65,   cpm_aceptable: 105,
    cpl_excelente: 100,  cpl_aceptable: 230,
    cpa_excelente: 200,  cpa_aceptable: 440,
    roas_excelente: 4,   roas_aceptable: 2,
    roi_excelente: 180,  roi_aceptable: 90,
    fuente: "Google Ads Professional Services 2024, Meta B2B Benchmarks",
  },
  manufactura_industria: {
    ctr_excelente: 2.0,  ctr_aceptable: 1.0,
    cpc_excelente: 4.0,  cpc_aceptable: 8.5,
    cpm_excelente: 50,   cpm_aceptable: 85,
    cpl_excelente: 85,   cpl_aceptable: 190,
    cpa_excelente: 180,  cpa_aceptable: 400,
    roas_excelente: 5,   roas_aceptable: 2.5,
    roi_excelente: 200,  roi_aceptable: 100,
    fuente: "WordStream Industrial 2024, Google Ads Manufacturing",
  },
  gastronomia_turismo: {
    ctr_excelente: 5.0,  ctr_aceptable: 2.5,
    cpc_excelente: 1.5,  cpc_aceptable: 3.5,
    cpm_excelente: 28,   cpm_aceptable: 52,
    cpl_excelente: 38,   cpl_aceptable: 85,
    cpa_excelente: 65,   cpa_aceptable: 145,
    roas_excelente: 7,   roas_aceptable: 3.5,
    roi_excelente: 250,  roi_aceptable: 120,
    fuente: "Meta Travel & Hospitality 2024, WordStream Travel LatAm",
  },
  servicios_profesionales: {
    ctr_excelente: 3.5,  ctr_aceptable: 1.8,
    cpc_excelente: 4.0,  cpc_aceptable: 8.5,
    cpm_excelente: 55,   cpm_aceptable: 90,
    cpl_excelente: 70,   cpl_aceptable: 160,
    cpa_excelente: 120,  cpa_aceptable: 270,
    roas_excelente: 5,   roas_aceptable: 2.5,
    roi_excelente: 200,  roi_aceptable: 100,
    fuente: "WordStream Professional Services 2024, Meta B2C LatAm",
  },
  tecnologia: {
    ctr_excelente: 3.0,  ctr_aceptable: 1.5,
    cpc_excelente: 5.5,  cpc_aceptable: 11.0,
    cpm_excelente: 65,   cpm_aceptable: 105,
    cpl_excelente: 90,   cpl_aceptable: 210,
    cpa_excelente: 180,  cpa_aceptable: 380,
    roas_excelente: 5,   roas_aceptable: 2.5,
    roi_excelente: 200,  roi_aceptable: 100,
    fuente: "WordStream Technology 2024, Google Ads Tech Industry Report",
  },
  transporte_logistica: {
    ctr_excelente: 3.0,  ctr_aceptable: 1.5,
    cpc_excelente: 3.0,  cpc_aceptable: 6.5,
    cpm_excelente: 45,   cpm_aceptable: 75,
    cpl_excelente: 65,   cpl_aceptable: 150,
    cpa_excelente: 130,  cpa_aceptable: 280,
    roas_excelente: 5,   roas_aceptable: 2.5,
    roi_excelente: 200,  roi_aceptable: 100,
    fuente: "Google Ads B2B LatAm 2024, WordStream Transportation",
  },
  agroindustria: {
    ctr_excelente: 2.0,  ctr_aceptable: 1.0,
    cpc_excelente: 2.0,  cpc_aceptable: 4.5,
    cpm_excelente: 32,   cpm_aceptable: 60,
    cpl_excelente: 60,   cpl_aceptable: 140,
    cpa_excelente: 140,  cpa_aceptable: 310,
    roas_excelente: 5,   roas_aceptable: 2.5,
    roi_excelente: 200,  roi_aceptable: 100,
    fuente: "Meta LatAm Agriculture 2024, Google Ads Agro Peru",
  },
  mineria_energia: {
    ctr_excelente: 1.5,  ctr_aceptable: 0.8,
    cpc_excelente: 6.0,  cpc_aceptable: 12.5,
    cpm_excelente: 70,   cpm_aceptable: 120,
    cpl_excelente: 130,  cpl_aceptable: 280,
    cpa_excelente: 290,  cpa_aceptable: 640,
    roas_excelente: 4,   roas_aceptable: 2,
    roi_excelente: 180,  roi_aceptable: 80,
    fuente: "Google Ads Industrial B2B 2024, Meta Mining & Energy LatAm",
  },
  seguridad: {
    ctr_excelente: 3.0,  ctr_aceptable: 1.5,
    cpc_excelente: 3.5,  cpc_aceptable: 7.5,
    cpm_excelente: 50,   cpm_aceptable: 85,
    cpl_excelente: 75,   cpl_aceptable: 170,
    cpa_excelente: 150,  cpa_aceptable: 340,
    roas_excelente: 5,   roas_aceptable: 2.5,
    roi_excelente: 200,  roi_aceptable: 100,
    fuente: "WordStream Home Services 2024, Meta Security LatAm",
  },
  otro: {
    ctr_excelente: 3.0,  ctr_aceptable: 1.5,
    cpc_excelente: 3.0,  cpc_aceptable: 7.0,
    cpm_excelente: 48,   cpm_aceptable: 82,
    cpl_excelente: 72,   cpl_aceptable: 165,
    cpa_excelente: 145,  cpa_aceptable: 320,
    roas_excelente: 5,   roas_aceptable: 2.5,
    roi_excelente: 200,  roi_aceptable: 100,
    fuente: "Promedio general Meta + Google Ads Peru 2024",
  },
};
